on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      branch: pages
    steps:
      - name: Prepare
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Cache
        uses: actions/cache@v2
        env: 
          cache-name: node-modules
        with: 
          path: ./node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      
      - name: Build
        run: |
          yarn
          yarn run build
          
      - name: Depoly
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with: 
          file: "dist/*"
          draft: false
          tags: true
