on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Cache
        uses: actions/cache@v2
        env: 
          cache-name: node-modules
        with: 
          path: ./node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      
      - name: Build
        run: |
          yarn
          yarn run build
          
      - name: Upload Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with: 
          file: "dist/*"
          draft: false
          tags: true

      - name: Depoly Builds
        env:
          repository: https://${{ secrets.TOKEN }}@github.com/innc11/AweCommentFiles
          branch: main
        run: |
          export datatime=`date +"%b %d, %Y %H:%M:%S"`
          cd dist
          git init
          git config user.email aprilforests@qq.com
          git config user.name innc11
          git status
          git remote add github $repository
          git checkout -b $branch
          git add --all
          git commit -m "Auto deploy from Github Actinos #$GITHUB_RUN_NUMBER on $datatime"
          git push github $branch --force
          echo "Successfully deployed!"
          echo "See: $repository/tree/$branch"
